# Generated by Django 4.1.3 on 2022-11-19 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_post_dislikes_post_likes_alter_post_author_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author_id',
            new_name='author',
        ),
    ]
